on:
  push:
    branches:
      - master      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOCKEN}}
      - name: " building docker "
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/javat:dev .
      - name: " pushing to docker hub "
        run: docker push ${{secrets.DOCKER_USERNAME}}/javat:dev
      