on:
  push:
    branches:
      - master1








jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd
      - name: 'Testing printing'
        run: echo dai